### ISSUE TITLE
0012656:
Auto-create links to Addresses

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6263]
**Reported by apvit on 14 Feb 2017 15:55**

**Version:** 2016.09.7 Community Edition

Button to open dialoge which shows 
- all addresses from the available addressbooks
- which contain at least one of the e-mail addresses in the respective mail.

Possibility to select one, several or all addresses.

Button to start function which automatically creates a link to all selected addresses.

**Comment by pschuele** [comment]
MailFiler will no longer be part of the community edition. The functionality will be moved to the Filemanager module. The MailFiler will be part of the https://github.com/tine20/tine20/tree/community_apps branch. Those apps should be moved to a separate repository at some point. The issues could be transferred there if still relevant. Closing this issue here.
