### ISSUE TITLE
0012658:
Inline graphics are not displayed

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6264]
**Reported by apvit on 14 Feb 2017 15:59**

**Version:** 2016.09.7 Community Edition

Inline graphics are not displayed in the preview of the mail.

**Steps to reproduce:** File email with inline graphics.
Click on filed email in MailFiler.

**Comment by pschuele** [comment]
MailFiler will no longer be part of the community edition. The functionality will be moved to the Filemanager module. The MailFiler will be part of the https://github.com/tine20/tine20/tree/community_apps branch. Those apps should be moved to a separate repository at some point. The issues could be transferred there if still relevant. Closing this issue here.
