### ISSUE TITLE
0012980:
More Mail-Functions in edit-properties-window

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6424]
**Reported by apvit on 26 Apr 2017 09:00**

Add the following buttons/functions in edit-properties-window:
- Reply
- Reply to all
- Forward

Purpose: Availability of these functions when opening a filed mail from a related record.

**Comment by pschuele** [comment]
MailFiler will no longer be part of the community edition. The functionality will be moved to the Filemanager module. The MailFiler will be part of the https://github.com/tine20/tine20/tree/community_apps branch. Those apps should be moved to a separate repository at some point. The issues could be transferred there if still relevant. Closing this issue here.
