### ISSUE TITLE
0013052:
Mails having charset KOI08 unreadable in Mailfiler

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6460]
**Reported by apvit on 11 May 2017 11:58**

**Version:** 2017.02.4 Community Edition

content encoded KOI08 (cyrillic)  is unreadable in mailfiler preview.

screenshot: 
left window = preview felamimail
rigth window = preview mailfiler

**Steps to reproduce:** add mail having charset KOI08 to mailfiler

**Comment by pschuele** [comment]
MailFiler will no longer be part of the community edition. The functionality will be moved to the Filemanager module. The MailFiler will be part of the https://github.com/tine20/tine20/tree/community_apps branch. Those apps should be moved to a separate repository at some point. The issues could be transferred there if still relevant. Closing this issue here.
