### ISSUE TITLE
0013118:
Improve Mailfiler performance

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6492]
**Reported by apvit on 23 May 2017 08:43**

Performance of module Mailfiler is poor, especially with large no. of records.

# Filing
Filing of mails from Felamimail to Mailfiler takes app. 1.8 seconds per record (tested with 400 records on an underutilized server at 9.00 p.m.).
That means: Filing of 100 mails takes app. 3 minutes, which is not very performant.

# Filtering
When a Folder has a large no. of records (i.e. 800 mails or more), the filter-process takes very long (at least 5-6 seconds) and even runs sometimes into a timout (depending on the complexity of the filter).

Note: Database maintainance is done weekly.

**Steps to reproduce:** Select a large no. of mails and file them.

Try to filter on a folder containing a large no. of mails.

**Comment by Gloirin** [comment]
Related to #6645

**Comment by pschuele** [comment]
MailFiler will no longer be part of the community edition. The functionality will be moved to the Filemanager module. The MailFiler will be part of the https://github.com/tine20/tine20/tree/community_apps branch. Those apps should be moved to a separate repository at some point. The issues could be transferred there if still relevant. Closing this issue here.
