### ISSUE TITLE
0013126:
PDF documents get corrupted when downloaded in Mailfiler

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6496]
**Reported by apvit on 23 May 2017 11:22**

**Version:** 2017.02.4 Community Edition

This problem occures with some mails.
PDF attachments get corrupted when downloaded in mailfiler. 
Filesize of corrupted PDF is increased in comparison to original.

**Steps to reproduce:** send attached example mail to Tine20
opening  attachment works
add mail to mailfiler
downloading or opening  attachment fails

**Additional information:** Tested:
sent same PDF from e.g. gmail to tine20  =&gt; attachment is OK in mailfiler
compared saved xy.eml in mail and mailfiler =&gt; .eml files identical
sent mail to Tine20 forwarded to gmail and forwarded back to Tine20 =&gt;  attachment is OK in mailfiler

**Comment by pschuele** [comment]
MailFiler will no longer be part of the community edition. The functionality will be moved to the Filemanager module. The MailFiler will be part of the https://github.com/tine20/tine20/tree/community_apps branch. Those apps should be moved to a separate repository at some point. The issues could be transferred there if still relevant. Closing this issue here.
