### ISSUE TITLE
0013442:
add "up" action again to nodes grid

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6649]
**Reported by pschuele on 14 Sep 2017 11:37**

add &quot;up&quot; action again to nodes grid

**Comment by pschuele** [comment]
MailFiler will no longer be part of the community edition. The functionality will be moved to the Filemanager module. The MailFiler will be part of the https://github.com/tine20/tine20/tree/community_apps branch. Those apps should be moved to a separate repository at some point. The issues could be transferred there if still relevant. Closing this issue here.
