### ISSUE TITLE
0013444:
headers of original message are not included on reply/reply all/forward

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6650]
**Reported by pschuele on 14 Sep 2017 11:40**

Headerdaten der Originalnachricht werden nicht übernommen (Von, An, Datum, Betreff).

Sollten die nicht standardmäßig übernommen werden?

**Comment by Gloirin** [comment]
**Comment posted by ebru on 15 Sep 2017 07:48**

Would also be useful in Felamimail.

**Comment by pschuele** [comment]
MailFiler will no longer be part of the community edition. The functionality will be moved to the Filemanager module. The MailFiler will be part of the https://github.com/tine20/tine20/tree/community_apps branch. Those apps should be moved to a separate repository at some point. The issues could be transferred there if still relevant. Closing this issue here.
