### ISSUE TITLE
0013520:
email body linebreaks missing in edit dialog

### ISSUE THREAD

**Issue by Gloirin** [tine20/tine20#6688]
**Reported by pschuele on 4 Oct 2017 09:57**

email body linebreaks missing in edit dialog

- breaks are visible in details panel

**Comment by pschuele** [comment]
MailFiler will no longer be part of the community edition. The functionality will be moved to the Filemanager module. The MailFiler will be part of the https://github.com/tine20/tine20/tree/community_apps branch. Those apps should be moved to a separate repository at some point. The issues could be transferred there if still relevant. Closing this issue here.
