### ISSUE TITLE
Event notifications are sent antichronological

### ISSUE THREAD

**Issue by lab-at-nohl** [tine20/tine20#6943]
When creating an event and changing it immediately, first the changing note is sent and afterwards the original invitation. In my case the delay was about 5 minutes. The problem is that the subject is changed (what for anyway?) and Outlook 2013 always uses the first incoming for its own subject. So the new event is called _Der Termin "Treffen Sven" wurde von 22.10.2018 20:00:00 auf 07.11.2018 20:00:00 verlegt_. 

Btw. creating a new event doesn't work using the new-button from another app (pulldown menu). Although a new window comes up, you can't submit (endless loop).

**Comment by pschuele** [comment]
are you using a setup with a queue + worker?
maybe this is just a mailserver issue? I'm quite sure that the tine20 code sends the "creation/invitiation" message before the "change" message.

i just did a small test and the mails where sent as expected:
![screenshot from 2018-10-26 12-42-54](https://user-images.githubusercontent.com/353947/47561817-af68e900-d91c-11e8-839c-5cd787a014ac.png)

> Btw. creating a new event doesn't work using the new-button from another app (pulldown menu). Although a new window comes up, you can't submit (endless loop).

this problem should be fixed in 2018.08.5 - see fe992b4cf906a462c6434edfb2dd541645d9e71c

**Comment by lab-at-nohl** [comment]
I can't believe, obviously the biggest provider for legal services uses gray listing as spam protection. 
http://postmaster.datev.de/greylisting/hilfe/

Sorry, please close this issue. The second mail goes faster because it is marked white instead of gray and therefor passes...

**Comment by pschuele** [comment]
ok :)

IMHO graylisting sucks ...
