### ISSUE TITLE
update apps without selection

### ISSUE THREAD

**Issue by rwkstgtd** [tine20/tine20#7157]
Hello,
after update from 2019.12.4 to 2019.12.5 I get the following error on the web interface: "Tine 2.0 muss aktualisiert werden oder ist noch nicht komplett installiert." (instead of the login mask, can't even enter user credentials).
Log sais (priority 7, debug):
```
16f2fc - -- none -- - 2020-03-01T17:48:40+00:00 INFO (6): Tinebase_Server_Http::handle::60 Is HTTP request. method: 
16f2fc - -- none -- - 2020-03-01T17:48:40+00:00 INFO (6): Tinebase_Frontend_Http::login::206 updates required
16f2fc - -- none -- - 2020-03-01T17:48:40+00:00 DEBUG (7): Tinebase_Frontend_Http::Tinebase_Frontend_Http::setupRequired (240) Update/Setup required!
```
On the setup interface (/setup) I can't update tinebase (I suppose this is what I should do, if I read the debug-log correctly). Tinebase is labeled "uptodate" and no update-option is present (update-command greyed out).

Can you fix this?

Best wishes
R. Köhler

**Comment by pschuele** [comment]
hi, thanks for the report. I'll check if I can reproduce the error.

**Comment by pschuele** [comment]
i see updates of Felamimail and Timetracker when updating from 2019.12.4 to 2019.12.5:
![Screenshot from 2020-03-02 12-39-18](https://user-images.githubusercontent.com/353947/75673326-f8ece500-5c82-11ea-99a2-7bc2b97e33a5.png)

after the update, I could login again.

you could also try to update from the command line, if the gui does not work:

```
php setup.php --config /path/to/tine20config --update

**Comment by rwkstgtd** [comment]
Hello pschuele,
I don't have felaminmail nor timetracker installed, so no updateble applications.
![grafik](https://user-images.githubusercontent.com/46139754/75686292-4f1a5200-5c9c-11ea-9c7e-edf2aa3bf1bc.png)
`php setup.php --config config.inc.php --update`
did the trick though.
With the php-command I get "Updated 1 application(s).", so there was indeed something to update, only the web interface didn't show.

Thanks for the help
R. Köhler

**Comment by pschuele** [comment]
ok, that looks like a bug. it should be possible to update via the gui, too. thanks for the report!

**Comment by asciuta** [comment]
Hello All,
I own the same problem on the update. But when i run
php setup.php --config /WebDirs/tine/config.inc.php --update
i got the error:
apache@hermes tine]$ php setup.php --config /WebDirs/tine/config.inc.php --update
Tinebase_Exception_UnexpectedValue: failed to create hash file in /WebDirs/tine/Tinebase/FileSystem.php:2202
Stack trace:
#0 /WebDirs/tine/Tinebase/FileSystem.php(617): Tinebase_FileSystem->createFileBlob(Resource id #815)
#1 /WebDirs/tine/Setup/Controller.php(2184): Tinebase_FileSystem->fclose(Resource id #815)
#2 /WebDirs/tine/Setup/Controller.php(2209): Setup_Controller->{closure}(Object(DirectoryIterator), Object(Tinebase_FileSystem), Object(Tinebase_Model_Tree_Node_Path))
#3 /WebDirs/tine/Setup/Controller.php(566): Setup_Controller->createImportExportDefinitions(Object(Tinebase_Model_Application), false)
#4 /WebDirs/tine/Setup/Controller.php(538): Setup_Controller->updateAllImportExportDefinitions()
#5 /WebDirs/tine/Setup/Frontend/Cli.php(452): Setup_Controller->updateApplications()
#6 /WebDirs/tine/Setup/Frontend/Cli.php(82): Setup_Frontend_Cli->_update(Object(Zend_Console_Getopt))
#7 /WebDirs/tine/Setup/Server/Cli.php(141): Setup_Frontend_Cli->handle(Object(Zend_Console_Getopt))
#8 /WebDirs/tine/Setup/Core.php(117): Setup_Server_Cli->handle()
#9 /WebDirs/tine/setup.php(14): Setup_Core::dispatchRequest()
#10 {main}
Sadly my php knowhow is not enough to find where this problem is really located.
Best Regards
H. Kueller

**Comment by asciuta** [comment]
Hello,
I found the error now. Sadly the errormessages are a bit unclear, cause in the output there is no path which is affected. 
In this case it was the path for the cloud storage. i use a nfs tree here.
in previous versions i was running the php setup.php --update command using root account. so it seems this changed the ownership of files in the cloud tree to root, and let tine not longer have write access there.
After i gave all the files back to apache:apache, the update worked fine!

Best Regards
H. Kueller
