### ISSUE TITLE
Cleanup deleted files

### ISSUE THREAD

**Issue by miwi0** [tine20/tine20#7166]
I have an installalation of tine20 on 2019.02.4.
Meanwhile I have al lot of files which are deleted in database but not in filesystem.
I would need help:
* how can I detect, if scheduler is running
* is there a CLI command to cleanup manually
Thanks!!!

**Comment by pschuele** [comment]
hi,

> how can I detect, if scheduler is running

you can check the scheduler runs by looking in the db table "tine20_scheduler". all jobs are listed there with last run timestamp, errors, ...

> is there a CLI command to cleanup manually

you can trigger the cleanup by running this CLI:

```
php tine20.php --method=Tinebase.clearDeletedFiles
```

**Comment by lab-at-nohl** [comment]
> you can trigger the cleanup by running this CLI:

php tine20.php --method=Tinebase.clearDeletedFiles

@pschuele This was news to me. Since ever I use `php tine20.php -d --method=Tinebase.purgeDeletedRecords -- date=$(date -d -365days +%Y-%m-%d)` to clean everything that is older than one year. Hereby I thought that would clear files, too. Additional I use method `Tinebase.clearTable` for credential_cache and access_log. 

What *services* do I need to run regularly?

**Comment by pschuele** [comment]
hi Johannes,
> Hereby I thought that would clear files, too.

you are right. I'll add the file cleanup to purgeDeletedRecords. the admin user expects that files are handled here, too.

> What services do I need to run regularly?

not sure about this question - the scheduler jobs should take care of that. the deleted file cleanup is a (daily) scheduler job. purgeDeletedRecords _removes_ records from the db, some people do not want this, so this is not redular scheduler job. you could also add your own scheduler jobs to the scheduler table (we might add a frontend for that at some point).
