### ISSUE TITLE
Softaculous Installation returns update loading page

### ISSUE THREAD

**Issue by w4cdev** [tine20/tine20#7179]
Install the app thru Softaculous on CentOS remote server, the project did not work having Config PHP 7.3 and MySQL 10.1.45
Error: Required MYSQL version greater than equal to 10.2.0 AND found version is : 10.1.45

TO overcome this issue tried manual install that was downloaded from [(https://github.com/tine20/tine20)] But this did not work and returned the loader error that reported "Tine 2.0 needs to be updated or is not installed yet."

If MySQL version is the only issue, then need to try with the downgrade package / repostory that matches the remote server config as above.

Greatly appreciate for help

**Comment by lab-at-nohl** [comment]
I do not have any experience with Softaculous. And I guess the DB version, you are refering to, is for **MariaDB** (the "better" MySQL-clone). 

I run a CentOS 7.8 (or 7.7, there was an update recently) but with the official MariaDB repos. This was necessary due to Tine 2.0 but flawless. I think the MySQL or MariaDB versions CentOS shipps with are pretty outdated. So if you are root on the machine I would recommend this way from my experience. 

However, to my knowledge earlier versions of MySQL/MariaDB should be still supported, see the [current README](https://github.com/tine20/tine20/blob/4c5f7259894bdf5ef0b6e9f4b96f7294bc88c971/README.md) that marks the versions as recommended only. But this might be a editorial mistake ;-)

**Comment by w4cadmin** [comment]
Thanks for your feedback.

Truly I appreciate your input,but the major issue as notified had same substantiate according to us

**Comment by lab-at-nohl** [comment]
> TO overcome this issue tried manual install that was downloaded from https://github.com/tine20/tine20 But this did not work and returned the loader error that reported "Tine 2.0 needs to be updated or is not installed yet."

Are you talking about this error? This is very general. First, use a fresh database (rmove all tables if you don't have any data in it). 

If that does not help, try to login to setup.php and update all apps. Please enable log file level DEBUG; try again and post the log file here.

**Comment by pschuele** [comment]
no more feedback here - closing the issue.
