### ISSUE TITLE
Alias-Adresse in SMTP

### ISSUE THREAD

**Issue by Mike-Sbg** [tine20/tine20#7183]
Possible I do somethin wrong, but I've the follow problem:

Wenn I admin a user, and enter a mail alias or a forward ... nothing happens.
No error, but the aliases / forwards are not inserted.

I use dovecot / postfix for Imap/SMTP with this specific user.

What's my error?

**Comment by markuspachali** [comment]
Hi @Mike-Sbg,
This sounds similar to my issue #7182. Which setup are you using? Are you also using a MySQL backend for Postfix and Dovecot?

**Comment by Mike-Sbg** [comment]
No Postfix and Dovecot are configured static

**Comment by lab-at-nohl** [comment]
You need a Mail Backend that supports additional fields. Hence, anything with MySQL or LDAP. Unfortunately you cannot see it by the Name of the Backend.

**Comment by Mike-Sbg** [comment]
OK thank you for the answer ... I don't like do use a dynamic configuration for postfix oder dovecot. 

So the only solution, is to define an extra (dummy) personal e-mail acoount, which can be used by the user, or is there an other possible way?

**Comment by lab-at-nohl** [comment]
Yes, use a second account if you cannot change your configuration. I don't see any other way. 

The dynamic configuration doesn't do much except to share its config with e.g. postfix. So simply speaking, the backend changes the database that is used by the mail server. Because, under the right circumstances, postfix would not let send you mails without having an alias configured. 

I know you can have this postfix config in text files, too. But atm there is no read only backend that can gather postfix's aliases (to my knowledge).

**Comment by Mike-Sbg** [comment]
OK thank you for the answer ... I've to figure out, what's the best solution for me.
