### ISSUE TITLE
Debian/Ubuntu packages packages list not updated?

### ISSUE THREAD

**Issue by hernot** [tine20/tine20#7186]
can it be that upon last release version number was not updated in apt packages list.

Tine itself reports that "2020.03 2020.03.3" version is available but package list is considered as not changed by apt as packagelist seems to recurr to Version: 2020.03.2-1.1804 with the result that nothing is updated.

![grafik](https://user-images.githubusercontent.com/11776325/84865816-223a5100-b079-11ea-8a69-8bea21983a82.png)

could it be that apt-repo was not updated at all or just packages list not loaded to apt-repo? Or is it that message is not correct as test for new versions does not recognize that installed version is already latest.

**Comment by lab-at-nohl** [comment]
As far as I know, packages are not updated whenever a new minor version is released. Thus, your system will stick with 2020.03.**2** whilst 2020.03.**3** has been publicly available. So disable the update notice might be an option (since your system would tell you if an update becomes available). 

Btw you could also overwrite the package's files by those from a zip. But you should know what you are doing (install files to the right place, update apps/db).

**Comment by hernot** [comment]
Ah Thank you.
Can you give me a quick hint where i find or have to put the setting for (de)activating the Notice.

**Comment by lab-at-nohl** [comment]
I have known it but I forgot. Must be somewhere here in the issues tracker...

**Comment by pschuele** [comment]
note: we only build community packages for the _latest_ ubuntu LTS release (which is 20.04 at the moment).
