### ISSUE TITLE
Tine uninstalled during Debian update to bullseye

### ISSUE THREAD

**Issue by Mr-Wolfe** [tine20/tine20#7324]
I have uptated Debian on web server to the new stable version Bullseye. During that process tine was unistalled. I could not install it via apt, since a lot of php7.3-... dependencies can not be installed.
The following packages have unmet dependencies:
 tine20-tinebase : Depends: php7.3-mysql but it is not installable or
                            php7.3-pgsql but it is not installable
                   Depends: php7.3-mbstring but it is not installable
                   Depends: php7.3-xml but it is not installable
                   Depends: php7.3-zip but it is not installable
                   Depends: php7.3-gd but it is not installable
                   Depends: php7.3-intl but it is not installable
                   Depends: php7.3-bcmath but it is not installable
                   Depends: php7.3-json but it is not installable
                   Depends: php7.3-cli but it is not installable
                   Recommends: php7.3-ldap but it is not installable

**Comment by cvantum** [comment]
Problably because there is no specific repository for Bullseye. According to the list of supported Debian Versions, this doesn't contain Bullseye ( https://packages.tine20.org/debian/dists/ ) Maybe this was deinstalled in a clean-up process.

I guess you should recover your system from a backup ( and stay on Buster until there is a official repository ) or install it manually.

You should also take a look if the mariadb is still installed as a dependency of tine.

**Comment by pschuele** [comment]
we added Bullseye in the meantime - so this should no longer be a problem. closing it.
