### ISSUE TITLE
tine uses shell_exec which is a security risk

### ISSUE THREAD

**Issue by mokraemer** [tine20/tine20#7352]
tine tries to exec "tnef" via shell_exec. This is a highly security risk to execute programs via shell and is forbidden by most servers.
This MUST be changed!

**Comment by mokraemer** [comment]
the function
Tinebase_Core::systemCommandExists
should
a) check if shell_exec is disabled (like vendor/ramsey/uuid/src/Provider/Dce/SystemDceSecurityProvider.php does)
b) shell_exec should not be used AT ALL

=> "tnef" as a systemcmd executed with the rights of the php process can introduce a security risk via buffer overflow.
If an "attachment" of outlook is found, the user should just be informed that the attachment is a propretary format and cannot be decoded. (off topic: I really never understood why this ever existed and why it is still activated by some users...)

**Comment by lab-at-nohl** [comment]
I would say it is only a POTENTIAL risk because the extracted attachment is only piped thru in the end, or? Thus, the overflow would take place in tnef/ytnef. 

However, I see your point and would recommend to not introduce a function in tine_core. Instead, keep everything at one place and hardcode it to tnef/ytnef. 

Also see if https://github.com/QualityUnit/TNEFDecoder is an alternative. 

However, you cannot ignore old school Outlook users in an business environment. I asked outlook users a while ago why people actively switch back from html mail to rich text. Answer: You can bring an attachment into context because the file has a position in text. Please keep the winmail.dat feature.

**Comment by pschuele** [comment]
yup, we'll keep the tnef functionality for the moment, as there are (sad but true) still lot's of outlook users out there that send winmail.dats ... :(
But I'll add a check for disabled shell_exec.

> Also see if https://github.com/QualityUnit/TNEFDecoder is an alternative.

might be - I think, it's worth a look.

**Comment by mokraemer** [comment]
a) shellexec is always a security risk. it gets executed with the rights of the php process, and winmail.dat is passed to that process, so any bug in this tool can lead to anything you expect from exploits
b) I know people use winmail.dat. for people openinng them in outlook again and use tine just to sync, there is no problem. connectors for iphone etc. still work to, as they decode the message themselves.
c) decoding of winmail.dat is just used for displaying inside the webfrontend and for indexing the file. both are sad but reflect the problem other mailers, e.g. like thunderbird (without plugin) have too. And just display the textpart of winmail.dat. So it is not absoulutly neccessary to decode winmail.dat.
