### ISSUE TITLE
Upgrade from 2021.02.3 to current nightly failed

### ISSUE THREAD

**Issue by has-sTeaLth** [tine20/tine20#7413]
If I try to update my installation (2021.02.3) with the current nightly one "tine-2022.11.19-4251243-nightly.tar.bz2" it failed with the following sql error:
`SQLSTATE[42S21]: Column already exists: 1060 Duplicate column name 'message_sent_copy_behavior', query was: ALTER TABLE 'tine20_felamimail_account' ADD COLUMN 'message_sent_copy_behavior' varchar(255) DEFAULT 'sent'`

For the update I proceeded as follows:
1. take backup of my current tine20 files and database.
2. moved the original tine20 folder and replaced it with the contents of nighty.
3. copied the config.inc.php file from the original to the newly created folder.
4. try to update with the following command `sudo -u webuser /opt/php-7.4/bin/php setup.php --update`

The installed applications are
![image](https://user-images.githubusercontent.com/46724790/203829902-709989cd-468b-4176-9850-761769579ec3.png)

Can anyone help me? Have I done something wrong? Is it not possible to upgrade directly to this version?

**Comment by ignoreigor** [comment]
Hi,

Your Felamimail-version is set to 15.2. The error message was thrown by function update003 in Felamimail/Setup/Update/15.php, added in 2022.09.03.58.

In 2021.02.3 the Felamimail-version could be only max. 14.1 . And Tinebase is  now15.20 (could be max. 14.7 in 2021.02.3 ) - so some updates between were already done.

You should have a look in your db to ensure that  the second modification (deletion of line in tine20_preferences WHERE name = "autoAttachNote") is made. If yes, all modifications of this updates are done and you could increase the Felamimail-version to 15.3 and "update tine20_application_tables set version=29 where name='felamimail_account';" to skip this update. Otherwise you could comment out the db-changes in source to skip these db-operations and let tine update application- and table-version.

**Comment by has-sTeaLth** [comment]
Hello @ignoreigor,
thanks for the reply. But after reading your reply, I realized that I made a big mistake in my first post.
I took the screenshot of the applications before restoring my database to the original (after update failed).

This is the correct one.
![image](https://user-images.githubusercontent.com/46724790/203924489-2472602f-52c7-4c7c-95df-d4857f162ee1.png)

I have now rechecked which version I tried to install last time. -> tine20-allinone_2021.12.1.tar.bz2
Was there felamimail-version 15.1?

How would you proceed?
I also tried to update the individual applications after the update and got the same SQL error.

**Comment by ignoreigor** [comment]
Hi,

yes, in release 2021.12.1 versions of Tinebase and Felamimail were 15.1 or rather 15.0.

The only change of field message_sent_copy_behavior is done in update003. Have a look in your not yet updated installation, whether this column already exists, though introduced in 2022.09.03.58. 

Otherwise it seems that this lines of code are passed two (or multiple) times, once updating the table, but not updating app- and/or felamimail_account-table-version and the second run throws this error that column does already exist. No idea why.

Maybe you can try an intermedia version to update to after 2022.09.03.58, maybe use  2022.09.10.137 - to see what'll happen.
Actually code for function update001-update003 has been changed and starts with Tinebase_TransactionManager::getInstance()->rollBack(); in newer versions, beginning with 2022.10.22.140

**Comment by lab-at-nohl** [comment]
I came from 20**21**.12.1 to 20**22**.12.1 and had the same message line about the duplicate column. But I definitely had not installed 2022.09.03.58 before. I guess, though, the update003 routine is triggered twice. 

However, at least in 2022.12.1 it seems to be only a warning. Just check if in the database the column exists and all fields are set to 'sent'... 

Sometimes it help to run `php setup.php --update` several times (not a professional advice but it worked in the past).

**Comment by crosenbe** [comment]
I have the same situation but it seems it's not only a warning. I tried to update from 2021.12.1 to 2022.12.1 as well.
And yes, field is available, but the database schema should move from 15 to 15.4?

**Comment by lab-at-nohl** [comment]
> And yes, field is available, but the database schema should move from 15 to 15.4?

Yes, definitely.

**Comment by has-sTeaLth** [comment]
Today I deleted the "message_sent_copy_behavior" and successfully updated to version Pino (2022.12.03.83).
