### ISSUE TITLE
nightly artifact is not attached to the latest release

### ISSUE THREAD

**Issue by ravermeister** [tine20/tine20#7435]
Hi, 
is there any reason why the final archive is not attached to the latest release?
the former release and all before had it attached as an artifact.

See the difference here:
[latest release](https://github.com/tine20/tine20/releases/tag/2023.01.14.325)
[former release](https://github.com/tine20/tine20/releases/tag/2022.12.17.79)

**Comment by byteplow** [comment]
The missing archive seems to be course by a registry hick up during packaging. This should not have been a problem for a next release. But saturday's release did not fix it. It failed because of broken end 2 end test. Which still are blocking the ci pipeline from building any release archives.

We should decouple packaging and from github release. So that we can still release archives manually, with out the need of manually building them.

**Comment by byteplow** [comment]
[Latest Saturdays](https://github.com/tine20/tine20/releases/tag/2023.01.28.39) release contains source packages again.
