### ISSUE TITLE
User Authentication IMAP didndt work

### ISSUE THREAD

**Issue by bopfi68** [tine20/tine20#7451]
Hello 

when changing user authentication to imap

Username Or Password Wrong

when i change setting to sql 
and use the same the Email Imap settings for Mailaccount it Works 

Imap is dovecot 
configured with ispconfig

also  installed rouncube mail work with imap fine    

versions:
postfix 3.6.4-1ubuntu1
dovecot-imapd/jammy-updates,jammy-security,now 1:2.3.16+dfsg1-3ubuntu2.1
tine-2023.02.04-0594f68

**Comment by lab-at-nohl** [comment]
Can you provide a logfile, level DEBUG? Do you use TLS/SSL?

**Comment by bopfi68** [comment]
normally i use ssl

see lo file
[tine-ImapSSLdebug.log](https://github.com/tine20/tine20/files/11128550/tine-ImapSSLdebug.log)

**Comment by lab-at-nohl** [comment]
Ok, I see. Which PHP Version do you use? Do you have access to the cli? Can you connect to IMAP using curl on that machine?

**Comment by bopfi68** [comment]
i testet with php 8.1, 7.4
same failure

i have access zu console, and curl
but which url, or command i had to check ?

**Comment by lab-at-nohl** [comment]
Try something like `curl --ssl-reqd imap://mail.example.com/inbox`. Curl uses the same certificates etc. like PHP. Also try without the parameter, since IMAP might refuse connection without. Then compare to your system account mail config in Tine 2.0. What is used there? Host, port, SSL...

I could not find anything unusual in the log file. However, please make sure if it is the same with PHP 8.1 as with 7.4! With PHP 8.1 a lot changed...

**Comment by lab-at-nohl** [comment]
Btw. your ActiveSync request shows more details. But still, it seems to be connection related. 

```
e85ea9 - -- none -- - 2023-04-01T07:45:40+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::133 Zend_Mail_Protocol_Exception -> cannot read - connection closed?
e85ea9 - -- none -- - 2023-04-01T07:45:40+00:00 ERR (3): Tinebase_Exception::logExceptionToLogger::155 #0 .../vendor/zendframework/zendframework1/library/Zend/Mail/Protocol/Imap.php(193): Zend_Mail_Protocol_Imap->_nextLine()
#1 .../vendor/zendframework/zendframework1/library/Zend/Mail/Protocol/Imap.php(135): Zend_Mail_Protocol_Imap->_assumedNextLine()
#2 .../vendor/zendframework/zendframework1/library/Zend/Auth/Adapter/Imap.php(223): Zend_Mail_Protocol_Imap->connect()
#3 .../vendor/zendframework/zendframework1/library/Zend/Auth.php(117): Zend_Auth_Adapter_Imap->authenticate()
#4 .../Tinebase/Auth.php(246): Zend_Auth->authenticate()
#5 .../Tinebase/Controller.php(121): Tinebase_Auth->authenticate()
#6 .../ActiveSync/Server/Http.php(209): Tinebase_Controller->login()
#7 .../ActiveSync/Server/Http.php(66): ActiveSync_Server_Http->_authenticate()
#8 .../Tinebase/Core.php(271): ActiveSync_Server_Http->handle()
#9 .../index.php(24): Tinebase_Core::dispatchRequest()
#10 {main}
e85ea9 - -- none -- - 2023-04-01T07:45:40+00:00 INFO (6): Tinebase_Log::logUsageAndMethod::298 {"file":"index.php","method":"ActiveSync_Server_Http::POST","time":"1m","memory":" Memory usage: 4 MB","cache":" Real patch cache size: 500","pid":208566}
```

**Comment by lab-at-nohl** [comment]
I testet IMAP auth with PHP 8.1.17 - works. 

I tried all combinations (none, TLS, SSL) against the ports (0, 143, 993). The error message "**cannot read - connection closed?**" meant, in my case, that either none or TLS was selected but port 993 (instead of 143) was given. All other combinations gave other, more meaningful, error messages.

From my point of view the issue can be closed.

**Comment by pschuele** [comment]
> From my point of view the issue can be closed.

ok, closing it. thx for testing @lab-at-nohl
