### ISSUE TITLE
Tine20 Adressbook export Import

### ISSUE THREAD

**Issue by bopfi68** [tine20/tine20#7464]
I want to Migrate tine20 to a new server with new databas

when export my personal addressbook to csv
its not possible to import 

for example 
exported csv looks empty fields looks like 
","","" 

the import example for empty entries looks like
,,,,,,

the tine own export is unable to import ?

is there a better way ?
-------------------------------------------

then i want to export by CLI

php -d memory_limit=512M /usr/share/tine20/tine20.php --config /etc/tine20/config.inc.php --username TineAdminUser --password PASSWORD  --method Addressbook.export > AdrAllExport.csv

get the error

Fatal error: Uncaught Tinebase_Exception_NotFound: Tinebase_Model_Container record with id = 1 not found! in /usr/share/tine20/Tinebase/Backend/Sql/Abstract.php:282

can you tell me the syntax for the Addressbook Container ID to Export ?

**Comment by lab-at-nohl** [comment]
> I want to Migrate tine20 to a new server with new databas

I am no expert for the import/export schema. However, given your description I assume that you did not provide the addressbook to export or your user is not allowed to find it; that's why Tine is looking for id `1` (internal contacts?). 

You can find the id of a container e.g. by right click / properties. Should be a long cryptic string. 

But you have to implement the id in code appearently:

> Per default only exports the internal contacts addressbook. You need to set the required container id in the code (Addressbook_Frontend_Cli).

See [Wiki on Cli functions](https://github.com/tine20/tine20/wiki/EN%3ACli#addressbookexport) 

+++

If your plan is to migrate an existing installation I would always make a backup and then try to upgrade tine 2.0. Afterwards move the whole database. I have never seen someone to move data only...

Best
Johannes

**Comment by bopfi68** [comment]
Hello Johannes

Migrating the complete Database was my forst idea also
but the databases had index failures
 unable to update 
so i want to have a new cliean installation

thanks for the link for cli dokumaentation 
worked wih´th this 

but cannot find the Details for:
 
Per default only exports the internal contacts addressbook. You need to set the required container id in the code (Addressbook_Frontend_Cli). 
 
thanks Andreas

**Comment by lab-at-nohl** [comment]
> but cannot find the Details for:
>
> Per default only exports the internal contacts addressbook. You need to set the required container id in the code (Addressbook_Frontend_Cli).

This tells you that you cannot set a different addressbook than `1` by CLI. A little strange but that's how it is. 

As the Wiki states, you may change the program code according to your needs... See [Addressbook/Frontend/Cli.php on line 211](https://github.com/tine20/tine20/blob/c27dadfaa30de519a87d9b4a112507338faae998/tine20/Addressbook/Frontend/Cli.php#L211) change `$containerId = 1;` to `$containerId = 'MY40CAHRSLONGSTRINGIDOFADDRESSBOOK';` (completely untested). Just try. 

Also, I cannot say how good import is. I guess you will loose at least any images but also not sure. 

---

> but the databases had index failures
> unable to update

I would always start with fixing that issues that you can update regularly...

**Comment by pschuele** [comment]
as we moved the issues, please open a new one here if the problem persists: https://github.com/tine-groupware/tine/issues.
